version: "3"
services:
    app:
        image: app
        container_name: app
        build:
            context: ./src/app
            dockerfile: ./Dockerfile
        ports:    
            - "5001:80"     
        networks:
            - appnet   
    worker:
        image: worker
        container_name: worker
        build:
            context: ./src/worker
            dockerfile: ./Dockerfile
        ports:    
            - "5005:80" 
        networks:
            - appnet        
    bus:
        image: mock
        container_name: mock-bus
        build:
            context: ./src/mock
            dockerfile: ./Dockerfile
        environment:
            MOCK_RANDOM: 300
        ports:    
            - "5002:80"     
        networks:
            - appnet
    mailer:
        image: mock
        container_name: mock-mailer
        build:
            context: ./src/mock
            dockerfile: ./Dockerfile
        environment:
            MOCK_RANDOM: 200
        ports:    
            - "5003:80"     
        networks:
            - appnet
    pay:
        image: mock
        container_name: mock-pay
        build:
            context: ./src/mock
            dockerfile: ./Dockerfile
        environment:
            MOCK_RANDOM: 100
        ports:    
            - "5004:80"     
        networks:
            - appnet
networks:
    appnet:   